name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        flavor: [mocha, macchiato, latte, frappe]
        accent:
          [
            rosewater,
            flamingo,
            pink,
            mauve,
            red,
            maroon,
            peach,
            yellow,
            green,
            teal,
            sky,
            sapphire,
            blue,
            lavender,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install colloid specific dependencies
        run: sudo apt update && sudo apt install -y sassc inkscape optipng
      - name: Generate themes
        run: python ./build.py ${{ matrix.flavor }} -a ${{ matrix.accent }} --zip -d $PWD/releases
      - name: Add zips to release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./releases/*.zip
